export enum KhatedarStatus {
  NEW = 'NEW',

  SURVEY_CREATED = 'SURVEY_CREATED',

  COMPENSATION_CREATED = 'COMPENSATION_CREATED',

  PAYMENT_FILE_CREATED = 'PAYMENT_FILE_CREATED',

  PAYMENT_DONE = 'PAYMENT_DONE',

  COURT_CASE = 'COURT_CASE',
}
