export enum KhatedarStatus {
  PENDING_FOR_SURVEY = 'PENDING_FOR_SURVEY',

  SURVEY_CREATED = 'SURVEY_CREATED',

  PENDING_FOR_COMPENSATION = 'PENDING_FOR_COMPENSATION',

  COMPENSATION_CREATED = 'COMPENSATION_CREATED',

  PENDING_FOR_PAYMENT = 'PENDING_FOR_PAYMENT',

  PAYMENT_DONE = 'PAYMENT_DONE',

  CLOSED = 'CLOSED',
}
